/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spotifei.View;

import spotifei.Dao.PlaylistDAO;
import spotifei.Model.Playlist;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author daniel.sobrinho
 */
public class PlaylistView extends javax.swing.JFrame {

    /**
     * Creates new form PlaylistView
     */
    public PlaylistView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nome_playlist = new javax.swing.JTextField();
        bt_criar_playlist = new javax.swing.JButton();
        bt_excluir_playlist = new javax.swing.JButton();
        bt_ver_musicas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_playlists = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_criar_playlist.setText("Criar");
        bt_criar_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_criar_playlistActionPerformed(evt);
            }
        });

        bt_excluir_playlist.setText("Excluir");
        bt_excluir_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluir_playlistActionPerformed(evt);
            }
        });

        bt_ver_musicas.setText("Ver músicas");
        bt_ver_musicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ver_musicasActionPerformed(evt);
            }
        });

        tabela_playlists.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabela_playlists);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bt_excluir_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_ver_musicas))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txt_nome_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(bt_criar_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nome_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_criar_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_excluir_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_ver_musicas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void bt_ver_musicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ver_musicasActionPerformed
        int linha = tabela_playlists.getSelectedRow();
    if (linha != -1) {
        int idPlaylist = (int) tabela_playlists.getValueAt(linha, 0);
        MusicasDaPlaylistView tela = new MusicasDaPlaylistView(idPlaylist);
        tela.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Selecione uma playlist para visualizar as músicas.");
    }

    }//GEN-LAST:event_bt_ver_musicasActionPerformed

    private void bt_criar_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_criar_playlistActionPerformed
        String nome = txt_nome_playlist.getText().trim();
        if (!nome.isEmpty()) {
            PlaylistDAO dao = new PlaylistDAO();
            dao.criarPlaylist(nome, idUsuario);
            atualizarTabela();
            txt_nome_playlist.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Digite um nome para a playlist.");
        }

    }//GEN-LAST:event_bt_criar_playlistActionPerformed

    private void bt_excluir_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluir_playlistActionPerformed
    int linha = tabela_playlists.getSelectedRow();
    if (linha != -1) {
        int idPlaylist = (int) tabela_playlists.getValueAt(linha, 0);
        String nomePlaylist = (String) tabela_playlists.getValueAt(linha, 1);

        int resposta = JOptionPane.showConfirmDialog(this,
            "Deseja excluir a playlist \"" + nomePlaylist + "\"?",
            "Confirmação",
            JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            PlaylistDAO dao = new PlaylistDAO();
            dao.excluirPlaylist(idPlaylist);
            atualizarTabela();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecione uma playlist para excluir.");
    }
    }//GEN-LAST:event_bt_excluir_playlistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaylistView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaylistView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaylistView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaylistView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaylistView().setVisible(true);
            }
        });
    }
    
    public void atualizarTabela() {
        PlaylistDAO dao = new PlaylistDAO();
        List<Playlist> playlists = dao.listarPlaylistsDoUsuario(idUsuario);

        DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Nome"}, 0);
        for (Playlist p : playlists) {
            model.addRow(new Object[]{p.getId(), p.getNome()});
        }

        tabela_playlists.setModel(model);
    }
    
    
    private int idUsuario;

    public PlaylistView(int idUsuario) {
        this.idUsuario = idUsuario;
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        atualizarTabela();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_criar_playlist;
    private javax.swing.JButton bt_excluir_playlist;
    private javax.swing.JButton bt_ver_musicas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabela_playlists;
    private javax.swing.JTextField txt_nome_playlist;
    // End of variables declaration//GEN-END:variables
}
